# =============================
# Halo Assistant Configurations
# =============================

audio:
  sample_rate: 16000
  duration: 5       # default recording time (seconds)
  vad: false        # use voice activity detection (true/false)

whisper:
  model: base       # options: tiny, base, small, medium, large
  device: cuda      # options: auto, cpu, cuda
  fp16: true        # use half precision on GPU (faster)

llm:
  provider: ollama  # options: ollama, openai, local
  model: qwen2.5:3b  # default model for Ollama / mistral / llama3.2:3b / phi3
  stream: false     # enable streaming response (future)
  

logging:
  save_transcripts: true
  transcript_dir: data/transcripts
  log_dir: data/logs

ui:
  theme: dark       # options: dark, light
  overlay: true     # floating overlay enabled

stt:
  provider: vosk      # or whisper
  model_path: "C:/Users/Hari/AppData/Local/vosk-model-en-in-0.5"

